### ISSUE TITLE
不要这么搞https://github.com/WinampDesktop/winamp/issues/2976

### ISSUE THREAD

**Issue by yangyangdaji2** [ccooder/ccooder#1]
@ccooder 
不要发表https://github.com/WinampDesktop/winamp/issues/2976 
 
 一我的账号被软封了 一点痕迹都没有，就算你关闭了也没用 
详情请看 https://bbs.deepin.org/phone/post/279961

**Comment by ccooder** [comment]
是不是因为你的账号注册时间比较新啊

**Comment by yangyangdaji2** [comment]
2022年我也做过贡献啥的，应该说他不算机器人账号才对。

![Screenshot_2024-10-31-09-31-42-691_com lemurbrowser exts-edit](https://github.com/user-attachments/assets/2acd0f23-72b9-4e1f-b9b8-cbc17b96e6dc)

**Comment by yangyangdaji2** [comment]
最生气的是他们不理我https://github.com/orgs/community/discussions/141499 这不是欺负新人吗
